### ISSUE TITLE
Run survtmle with one treatment arm

### ISSUE THREAD

**Issue by ernestatistics** [benkeser/survtmle#34]
I am trying to estimate cumulative incidence in a survival setting without any treatment arms. Would it be possible to run survtmle without having to specify a treatment variable? Or what would be the best way to approach this? 

Thanks,

Ernesto

**Comment by benkeser** [comment]
Hmm, do you need to do super learning or are glm's OK?

If GLM's are OK, then you could just include a dummy column for `trt` (e.g., all 1's) set `trtOfInterest = 1` and then omit `trt` from your `glm` formula. Seems like that might work.

Super learning may be more complicated. But maybe not. One could include a dummy column for `trt`, set `trtOfInterest` and then write a screening wrapper for `SuperLearner` that looks for the `trt` column and removes it. This would ensure that none of the learners misbehave due to having a column of all 1's. 

Not 100% sure that either of these will work. But it's a starting place.

**Comment by ernestatistics** [comment]
Thanks David, we would like to do super learning. I will try both approaches and let you know how it goes.

**Comment by benkeser** [comment]
Any follow up on this?

**Comment by benkeser** [comment]
Closing for now. Can reopen if I hear back from you @ernesto-up
